---
title: 'Teva memory - myeloid cells - visualization'
author: "Sarah"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    fig_crop: no
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
editor_options:
  
  chunk_output_type: console
---

## 1. tSNE plot
```{r message=FALSE, warning=FALSE, cache=FALSE, fig.width=10, fig.height= 10}
library(dplyr)
library(Seurat)
library(patchwork)
library(tidyverse)
library(sleepwalk)
library(gridExtra)
library(future)
library(reshape2)
library(plyr)
library(stringr)
library(RColorBrewer)
library(grid)
library(cowplot)
library(ggsignif)
library(DT)
library(Cairo)
library(snakecase)
#install.packages("snakecase")
memory.limit(10^14)
setwd("//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/3_groups")
x1 <- 4

myeloid_cells = readRDS(file="Objects/Teva_myeloid_intermediate_object.rds")
table(myeloid_cells$orig.ident)
```


```{r echo=FALSE, fig.width=6, fig.height= 6}
DimPlot(myeloid_cells, reduction = "tsne", label= TRUE, pt.size=0.5)
ggsave(file = "Plots/myeloid/tSNE_unannotated.png", dpi=300, width=6, height=6)
```

Top DE genes
--------------
```{r echo=FALSE}
Top50Markers <- read.delim("//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/3_groups/Excels/memory_myeloid_DE_genes.csv", sep = ",", header = T, quote="\"", check.names=FALSE)
Top50Markers$avg_log2FC <- Top50Markers$avg_log2FC %>% round(2)
Top50Markers <- Top50Markers[,c("cluster","gene", "avg_log2FC", "p_val")] 
datatable(Top50Markers, rownames = FALSE, filter = 'top', colnames = c('Cluster #', 'Gene Name', "log2(FC)", 'P.value'))
```

## 2. Subpopulations identification
### a. T cells
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=16, fig.height= 18}

#install.packages("scCustomize")
library(scCustomize)

#install.packages("qs")
library(qs)

FeaturePlot(myeloid_cells, features = c("Ptprc", "Cd3e", "Cd8a", "Cd4", "Foxp3"), order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "Plots/myeloid/Features_T.png", dpi=300, width=16, height=10)
```


### b. neutrophils
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=12, fig.height= 6}
FeaturePlot(myeloid_cells, features = c("S100a8", "S100a9", "Retnlg", "Ccl3"), order=TRUE,pt.size=1, label= T, reduction="tsne", ncol=2)

FeaturePlot(myeloid_cells, features = c("S100a8", "S100a9", "Retnlg"), order=TRUE,pt.size=1, label= T, reduction="tsne", ncol=3)
ggsave(file = "Plots/myeloid/features_neutrophils.png", dpi=300, width=16, height=6)
```




### c. mature DCs
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=16, fig.height= 6}
FeaturePlot(myeloid_cells, features = c("Ccl5", "Fscn1", "Ccr7"), order=TRUE,pt.size=1, label= T, reduction="tsne", ncol=3)
ggsave(file = "Plots/myeloid/features_mature_DC.png", dpi=300, width=16, height=6)
```



### d. monocytes
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=16, fig.height= 16}
FeaturePlot(myeloid_cells, features = c("Ccr2", "Itgax", 'Itgam', 'Cx3cr1', 'Apoe', "Ly6c2", "Plac8", "Prtn3"), order=TRUE,pt.size=1, label= T, label.size = 6, reduction="tsne", ncol=3)
ggsave(file = "Plots/myeloid/features_monocytes.png", dpi=300, width=18, height=18)
```


### e. Macrophages
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=16, fig.height= 16}
FeaturePlot(myeloid_cells, features = c('Cd68','Fcgr3','Fcgr1','Ccl17','C1qa','Fcrls','Cxcl16','Ccr5','Ccl12','Mafb',
          'Chil3','Il18'), order = T, pt.size=1, label= T, label.size = 6, reduction="tsne", ncol=3)



FeaturePlot(myeloid_cells, features = c('C1qa','Cxcl16','Ccl12'), order = T, pt.size=1, label= T, label.size = 6, reduction="tsne", ncol=3)
ggsave(file = "Plots/myeloid/features_M1.png", dpi=300, width=16, height=6)


FeaturePlot(myeloid_cells, features = c('Chil3','Il18'), order = T, pt.size=1, label= T, label.size = 6, reduction="tsne", ncol=2)
ggsave(file = "Plots/myeloid/features_M2.png", dpi=300, width=10, height=6)

```

### f. cDC1 Dendritic cells 
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=10, fig.height= 10}
DC1 <- c('Cd80', 'Cd83', 'Icam1')
FeaturePlot(myeloid_cells,label= T, features = DC1, label.size = 6, pt.size = 1 , ncol = 2, order = T,reduction = "tsne")
ggsave(file = "Plots/myeloid/cDC1.png", dpi=300, width=16, height=16)
```

### g. cDC2 Dendritic cells
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=14, fig.height= 8}
DC2 <- c('Slamf7','Itgax','Irf4','Il1r2','Dab2','Ccr1','Ifitm1')
FeaturePlot(myeloid_cells,label= T, features = DC2, label.size = 6, pt.size = 1 , ncol = 3, order = T,reduction = "tsne")


FeaturePlot(myeloid_cells,label= T, features = c('Itgax','Il1r2','Ifitm1'), label.size = 6, pt.size = 1 , ncol = 3, order = T,reduction = "tsne")
ggsave(file = "Plots/myeloid/cDC2.png", dpi=300, width=14, height=6)
```

### h. Granulocytes 
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=8, fig.height= 4}
Granulocytes <- c('S100a8', 'S100a9')
FeaturePlot(myeloid_cells, label= T, features = Granulocytes, label.size = 6, pt.size = 1 , ncol = 2, order = T,reduction = "tsne")
ggsave(file = "Plots/myeloid/Granulocytes.png", dpi=300, width=16, height=16)
```

### i. NK Cells 
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=12, fig.height= 8}
NKs <- c('Itga2','Ncr1', 'Klrd1',"Gzma", "Prf1","Gzmb")
FeaturePlot(myeloid_cells, features = NKs, label.size = 6, pt.size = 1 ,label= T,  ncol = 3, order = T,reduction = "tsne")
ggsave(file = "Plots/myeloid/NK1.png", dpi=300, width=16, height=16)

### Nk hunt
nk <- c('Cd226', 'Ncr1', 'Klrb1c', 'Clec5c ','Klrk1', 'Ncam1', 'Klrd1', 'Il2rb', 'Cd127', 'Cd16', "Nkg2a", "Ncr3", "Ncr2")
FeaturePlot(myeloid_cells, features = nk, label.size = 6, pt.size = 1, ncol = 3, order = T,reduction = "tsne")
ggsave(file = "Plots/myeloid/NK2.png", dpi=300, width=16, height=16)

```

### j. B Cells
```{r cache=T, fig.height=2*2, echo=T, fig.width=12, fig.height= 8}
B_cells <- c('Cd19','Cd74','Cd79a','Ebf1','Ighm')
FeaturePlot(myeloid_cells, features = B_cells, label.size = 6, pt.size = 1 ,label=T, ncol = 3, order = T,reduction = "tsne")

FeaturePlot(myeloid_cells, features = c('Cd19','Cd79a','Ebf1'), label.size = 6, pt.size = 1 ,label=T, ncol = 3, order = T,reduction = "tsne")
ggsave(file = "Plots/myeloid/B.png", dpi=300, width=16, height=6)
```


### k. Cxcl16+Cxcl10
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=4, fig.height= 4}
FeaturePlot(myeloid_cells, features = c("Cxcl16"),pt.size=1, reduction="tsne")
ggsave(file = "plots/myeloid/Cxcl16_feature.png", dpi=300, width=6, height=6)

VlnPlot(myeloid_cells, features = c("Cxcl16"), group.by = "Treatment", fill.by ="ident")+theme(axis.text.y =element_text(size=4))+ theme_classic()+theme(axis.text.x = element_text(angle = 70, hjust=1, size=12), axis.title.x = element_blank()) + theme(axis.title.y=element_text(size=12))+
    scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
geom_boxplot(alpha=0.3,show.legend = FALSE)
ggsave(file = "plots/myeloid/Cxcl16_vln.png", dpi=300, width=6, height=6)


FeaturePlot(myeloid_cells, features = c("Cxcl10"),pt.size=1, reduction="tsne")
ggsave(file = "plots/myeloid/Cxcl10_feature.png", dpi=300, width=6, height=6)

VlnPlot(myeloid_cells, features = c("Cxcl10"), group.by = "Treatment", fill.by ="ident")+theme(axis.text.y =element_text(size=4))+ theme_classic()+theme(axis.text.x = element_text(angle = 70, hjust=1, size=12), axis.title.x = element_blank()) + theme(axis.title.y=element_text(size=12))+
   scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
geom_boxplot(alpha=0.3,show.legend = FALSE)
ggsave(file = "plots/myeloid/Cxcl10_vln.png", dpi=300, width=6, height=6)


# how to find gene names in seurat(check if exists)
#grep("^Ccl16",rownames(myeloid_cells@assays$RNA@counts),value = TRUE)
```

### trying stuff
```{r}
FeaturePlot(myeloid_cells, features =c("Faap20", 'Fcho1', 'Nab1', 'Ccdc88b', 'Cmtr1', 'Tnfrsf21', 'Gpcpd1'), order=TRUE,pt.size=1, reduction="tsne", ncol=3)

c("Faap20", 'Fcho1', 'Nab1', 'Ccdc88b', 'Cmtr1', 'Tnfrsf21', 'Gpcpd1')

FeaturePlot(myeloid_cells, features =c("Chil3", "Cxcl10", "Vcan", "Ccr5", "Il18","Thbs1","Plcb1","Cacna1d","Pnp"), order=TRUE,pt.size=1, reduction="tsne", ncol=3)

cluster0_list = list(c("Cxcl10", "Vcan", "Il18","Plcb1","Cacna1d"))
myeloid_cells = AddModuleScore(object = myeloid_cells, features = cluster0_list, name = "Cxcl10")
a <- FeaturePlot(object = myeloid_cells, features = "Cxcl101", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "0_ Cxcl10+ myeloid cells", subtitle = "(Cxcl10, Vcan, Il18,Plcb1,Cacna1d)")+ theme(plot.subtitle = element_text(hjust = 0.5))
ggsave(file = "plots/myeloid/cluster0_Cxcl10.png", dpi=300, width=5, height=5)

cluster1_list = list(c("C1qa", "Ccl12", "Cxc16"))
myeloid_cells = AddModuleScore(object = myeloid_cells, features = cluster1_list, name = "M2_mac")
b <- FeaturePlot(object = myeloid_cells, features = "M2_mac1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "1_ M2-like", subtitle = "(C1qa, Ccl12, Cxc16)")+ theme(plot.subtitle = element_text(hjust = 0.5))
ggsave(file = "plots/myeloid/cluster1_M2-like.png", dpi=300, width=5, height=5)

cluster2_list = list(c("Chil3", "Tmem26", "Gpcpd1", "Tnfrsf21"))
myeloid_cells = AddModuleScore(object = myeloid_cells, features = cluster2_list, name = "M1_mac")
c <- FeaturePlot(object = myeloid_cells, features = "M1_mac1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "2_ M1-like", subtitle = "(Chil3, Tmem26, Gpcpd1, Tnfrsf21)")+ theme(plot.subtitle = element_text(hjust = 0.5))
ggsave(file = "plots/myeloid/cluster2_M1-like.png", dpi=300, width=5, height=5)

cluster3_list = list(c("Ccl5", "Fscn1", "Ccr7", "Cd80", "Cd83"))
myeloid_cells = AddModuleScore(object = myeloid_cells, features = cluster3_list, name = "cDC1")
d <- FeaturePlot(object = myeloid_cells, features = "cDC11", reduction = "tsne",cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "3_ cDC-1", subtitle = "Ccl5, Fscn1, Ccr7,Cd80, Cd83")+ theme(plot.subtitle = element_text(hjust = 0.5))
ggsave(file = "plots/myeloid/cluster3_cDC-1.png", dpi=300, width=5, height=5)

cluster4_list = list(c("Cd209a", "Batf3", "Cxcl9", "Ccr2","Ifitm1"))
myeloid_cells = AddModuleScore(object = myeloid_cells, features = cluster4_list, name = "cDC2")
e <- FeaturePlot(object = myeloid_cells, features = "cDC21", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "4_ cDC-2", subtitle = "(Cd209a, Batf3, Cxcl9, Ccr2, Ifitm1)")+ theme(plot.subtitle = element_text(hjust = 0.5))
ggsave(file = "plots/myeloid/cluster4_cDC-1.png", dpi=300, width=5, height=5)

cluster5_list = list(c("Cd19", "Ighm", "Cd79a", 'Ebf1'))
myeloid_cells = AddModuleScore(object = myeloid_cells, features = cluster5_list, name = "B_cells")
f <- FeaturePlot(object = myeloid_cells, features = "B_cells1", reduction = "tsne",cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "5_ B cells", subtitle = "Cd19, Ighm, Cd79a, Ebf1")+ theme(plot.subtitle = element_text(hjust = 0.5))
ggsave(file = "plots/myeloid/cluster5_B cells.png", dpi=300, width=5, height=5)

cluster6_list = list(c("S100a9", "Ccl3", 'S100a8', "Retnlg"))
myeloid_cells = AddModuleScore(object = myeloid_cells, features = cluster6_list, name = "neutrophils")
g <- FeaturePlot(object = myeloid_cells, features = "neutrophils1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "6_ Neutrophils", subtitle = "S100a9, Ccl3, S100a8, Retnlg")+ theme(plot.subtitle = element_text(hjust = 0.5))
ggsave(file = "plots/myeloid/cluster6_neutrophils.png", dpi=300, width=5, height=5)

(a|b|c|d)/
  (e|f|g|plot_spacer())
ggsave(file = "plots/myeloid/myeloid_features.png", dpi=300, width=20, height=10)



FeaturePlot(myeloid_cells, features =c("Batf3", 'Ccr2', 'Cd11b', 'Cd1a', 'Cmtr1', 'Cd1c', 'Cd24a', 'Cd70', 'Cd80', 'Cd83', 'Cd86', 'Csfr2', 'Cxcl9',"Cxcr3", 'Cd209a'), order=TRUE,pt.size=1, reduction="tsne", ncol=3)

```

dcsign
flt3
h2-dmb2
id2
il12
irf4
mgl2
notxh2
ox40l
sirpa
zbtb46
CLEC10A
CD1C
BHLHE40

#e46467'

Gstt4
M22Rik
Tnfrsf21
Nfxl1
Pim2
Map3k14
Cxcl16
Kif13b
Slc6a13
Scamp1
Tpd52
Ssh1



## 3. Target markers
```{r fig.height=x1*1, fig.width=12, echo=FALSE}
TargetMarkers <- c('Il2ra','Il2rb','Pdcd1')
FeaturePlot(myeloid_cells, features = TargetMarkers, label= T,pt.size = 1.2 ,ncol = 2, order = T, reduction = 'tsne')
ggsave(file = "plots/myeloid/Features_targets.png", dpi=300, width=10, height=10, limitsize=FALSE)


VlnPlot(myeloid_cells, features = c('Il2ra'), flip= TRUE, split.by = "Treatment")+
  theme(axis.text.y =element_text(size=6),
        axis.text.x = element_text(angle = 70, hjust=1, size=12), axis.title.x = element_blank(),
        axis.title.y=element_text(size=12))+ 
  theme_classic() +
     scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
  geom_boxplot(alpha=0.3,show.legend = FALSE)
ggsave(file = "plots/myeloid/Vln_Il2ra.png", dpi=300, width=10, height=10, limitsize=FALSE)

VlnPlot(myeloid_cells, features = c('Il2rb'), flip= TRUE, split.by = "Treatment")+
  theme(axis.text.y =element_text(size=6),
        axis.text.x = element_text(angle = 70, hjust=1, size=12), axis.title.x = element_blank(),
        axis.title.y=element_text(size=12))+ 
  theme_classic() +
     scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
  geom_boxplot(alpha=0.3,show.legend = FALSE)
ggsave(file = "plots/myeloid/Vln_Il2rb.png", dpi=300, width=10, height=10, limitsize=FALSE)

VlnPlot(myeloid_cells, features = c('Pdcd1'), flip= TRUE, split.by = "Treatment")+
  theme(axis.text.y =element_text(size=6),
        axis.text.x = element_text(angle = 70, hjust=1, size=12), axis.title.x = element_blank(),
        axis.title.y=element_text(size=12))+ 
  theme_classic() +
     scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
  geom_boxplot(alpha=0.3,show.legend = FALSE)
ggsave(file = "plots/myeloid/Vln_Pdcd1.png", dpi=300, width=10, height=10, limitsize=FALSE)


VlnPlot(myeloid_cells, features = c('Cd274'), flip= TRUE, split.by = "Treatment")+
  theme(axis.text.y =element_text(size=6),
        axis.text.x = element_text(angle = 70, hjust=1, size=12), axis.title.x = element_blank(),
        axis.title.y=element_text(size=12))+ 
  theme_classic() +
     scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
  geom_boxplot(alpha=0.3,show.legend = FALSE)
ggsave(file = "plots/myeloid/Vln_PD-L1.png", dpi=300, width=10, height=10, limitsize=FALSE)
```


## 4. Annotation
```{r eval=FALSE, fig.height=6, fig.width=6, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
myeloid_cells@active.ident = myeloid_cells$seurat_clusters
DimPlot(myeloid_cells, reduction = "tsne", label=T, pt.size=0.5, label.size = 6)
ggsave(file = "Plots/myeloid/annotated tsne - no names.png",path= "plots", dpi=300, width=6, height=6)

myeloid_cells@active.ident = myeloid_cells$seurat_clusters
myeloid_cells = RenameIdents(myeloid_cells, 
                       "0" = "0_C1qa+ Myeloid cells", 
                       "1" = "1_C1q", 
                       "2" = "2_yet", 
                       "3" = "3_mature DCs", 
                       "4" = "4_cDC-2", 
                       "5" = "5_Neutrophils",
                       "6" = "6_B cells")
DimPlot(myeloid_cells, reduction = "tsne", label=TRUE, pt.size=0.5, label.size = 4)
ggsave(file = "Plots/myeloid/annotated tsne - with names.png", dpi=300, width=12, height=6)

saveRDS(myeloid_cells, file = "//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/ateno+saline/Objects/Teva_myeloid_object.rds")
```

## 5. Contribution of each group
```{r eval=FALSE, fig.height=10, fig.width=15, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
# without normilization : 
ggplot(myeloid_cells@meta.data, aes(x=myeloid_cells@active.ident, fill=Treatment)) + geom_bar(position="fill")+
    scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
    theme_classic()+
    labs(x="")+
    ggtitle("Before normalization") +
    theme(legend.title=element_text(size=24),
          legend.text= element_text(size=24), 
          axis.text.x=element_text(size=24,angle=45, hjust=1), 
          axis.text.y=element_text(size=16), axis.title.y=element_text(size=16), title = element_text(size = 20))
ggsave(file = "Plots/myeloid/stacked bar plot - before normalization.png", dpi=300, width=20, height=10)

##
frque <- table(Idents(myeloid_cells), myeloid_cells$Sample)
frque <- as.data.frame(frque)
frque <- frque %>% 
  dplyr::rename(Cluster = Var1, Sample = Var2)
f1 <- subset(frque, Sample=='D')

frque <- ddply(frque, .(Sample), transform, percentperstatus = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, percentpercluster = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, normalizedppstatus = percentperstatus/sum(percentperstatus)*100)
frque$Treatment <- with(frque, ifelse(Sample=="A", "αPD1-Il2","Saline"))
# frque <- ddply(frque, .(Sample), transform, normalizedpcluster = percentpercluster/sum(percentpercluster))

p1 <- ggplot(frque, aes(x= Cluster, y= normalizedppstatus, fill = Treatment)) + 
  geom_bar(stat = "identity", width = 0.7) +
  theme_classic()+
  scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
  ggtitle("Normalized Cluster Counts") +
  ylab("Normalized Proportions in %") +
  theme(
    axis.text.x = element_text(size = 18, color="black", angle = 45, hjust = 1),
    axis.text.y = element_text(size = 18, color="black"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 18, color="black"),
    legend.text = element_text(size=14),
    title = element_text(size = 20),
    legend.justification = "top",
    panel.border = element_blank()) +
  geom_hline(yintercept = 50, linetype='dotted') +
  annotate("text", x = levels(myeloid_cells@active.ident)[length(levels(myeloid_cells@active.ident))], y = 50, 
           label = "50%", vjust = -0.5)

p1
ggsave(file = "Plots/myeloid/normalized_bar.png", dpi=300, width=16, height=10)

p2<-ggplot(frque, aes(x= Cluster, y= Freq, fill = Treatment)) + 
  theme_classic() +
  geom_bar(stat = "identity", width = 0.7) +
  ggtitle("Cluster Counts") + ylab("Cell counts\n") +
    scale_fill_manual(values= c("#CFBAE1", "#5C7D9D","#A4DEF9"))+
  theme(
    axis.text.x = element_text(size = 12, color="black", angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12, color="black"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 15, color="black"),
    title = element_text(size = 13),
    legend.justification = "top",
    panel.border = element_blank())
p2
ggsave(file = "Plots/myeloid/contribution_absuloute_barplot.png", dpi=300, width=6, height=6)

grid.arrange(p2,p1, nrow= 1)



TSNEPlot(myeloid_cells, group.by ="Treatment", cols= c("#CFBAE1", "#5C7D9D","#A4DEF9"), pt.size=0.5)
ggsave("Plots/myeloid/tSNE - by treatment.png", dpi=300, width=8, height=8)


```






## 5. Tomers markers

### MHC class 1 Markers
```{r fig.height=x1*2, fig.width=12, echo=FALSE}
MHC1Markers <- c('H2-D1','H2-K1','H2-M3','H2-Q4','H2-Q6','H2-Q7')
FeaturePlot(myeloid_cells, features = MHC1Markers, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

```{r echo=FALSE, fig.height=x1*4, fig.width=10, message=FALSE, warning=FALSE}
p1 <- VlnPlot(myeloid_cells, features = 'H2-D1', split.by = 'Sample' , pt.size = 0)
p2 <- VlnPlot(myeloid_cells, features = 'H2-K1', split.by = 'Sample' , pt.size = 0)
p3 <- VlnPlot(myeloid_cells, features = 'H2-Q6', split.by = 'Sample' , pt.size = 0)
p4 <- VlnPlot(myeloid_cells, features = 'H2-Q7', split.by = 'Sample' , pt.size = 0)
grid.arrange(p1,p2,p3,p4,ncol = 1)
```

### MHC class 2 Markers
```{r fig.height=x1*2, fig.width=12, echo=FALSE}
MHC2Markers <- c('H2-Ab1','H2-Eb1','H2-DMb1','H2-DMb2','H2-DMa')
FeaturePlot(myeloid_cells, features = MHC2Markers, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

```{r echo=FALSE, fig.height=x1*3, fig.width=10, message=FALSE, warning=FALSE}
p1 <- VlnPlot(myeloid_cells, features = 'H2-Ab1', split.by = 'Sample' , pt.size = 0)
p2 <- VlnPlot(myeloid_cells, features = 'H2-Eb1', split.by = 'Sample' , pt.size = 0)
p3 <- VlnPlot(myeloid_cells, features = 'H2-DMb1', split.by = 'Sample' , pt.size = 0)
grid.arrange(p1,p2,p3,ncol = 1)
```

### Monocytes
```{r fig.height=x1*2, fig.width=12, echo=FALSE}
Monocytes <- c('Cd14','Fcna','Lyz1','Vcan')
FeaturePlot(myeloid_cells, features = Monocytes, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```


### pDCs
```{r fig.height=x1*4, fig.width=12, echo=FALSE}
pDCs <- c('Cox6a2','Ly6d','Siglech','Ccr9','Ly6c1','Ly6c2','Ctsl','Bst2','Il3ra','Lilrb4a','Clec4d','Il12a','Ccr7')
FeaturePlot(myeloid_cells, features = pDCs, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

```{r fig.height=x1*2, fig.width=9, echo=FALSE, warning=FALSE}
p1 <- VlnPlot(myeloid_cells, features = 'Cox6a2', split.by = 'Sample' , pt.size = 0)
p2 <- VlnPlot(myeloid_cells, features = 'Ly6d', split.by = 'Sample' , pt.size = 0)
p3 <- VlnPlot(myeloid_cells, features = 'Siglech', split.by = 'Sample' , pt.size = 0)
grid.arrange(p1,p2,p3,ncol = 1)
```

### cDC1
```{r fig.height=x1*3, fig.width=12, echo=FALSE}
DC1 <- c('H2-Ab1','H2-Eb1','Clec9a','Xcr1','Irf8','Rab7b','Naaa','Stmn1','Ppt1')
FeaturePlot(myeloid_cells, features = DC1, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

### cDC1- Ayelet genes
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6301092/
```{r fig.height=x1*5, fig.width=12, echo=FALSE}
DC1 <- c('Csf2rb', 'Ccr7', 'Ccl22', 'Fscn1', 'Ly75', 'Batf3', 'Cd80', 'Cd83', 'Icam1', 'Il12b', 'Flt3', 'H2-DMb2', 'Zbtb46')
FeaturePlot(myeloid_cells, features = DC1, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

### cDC2
```{r fig.height=x1*4, fig.width=12, echo=FALSE}
DC2 <- c('Fcer1a','Itgax','Cd209a','Cd209d','Irf4','Mmp12','Clec4n','Il1r2','Dab2','Mgl2','Ccr1','Ifitm1')
FeaturePlot(myeloid_cells, features = DC2, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

### cDC3
```{r fig.height=x1*4, fig.width=12, echo=FALSE}
# grep(rownames(myeloid_cells), pattern = "Lilrb", value = T)
DC3 <- c('Fscn1','Ccl5','Ccr7','Cacnb3','Anxa3','Tmem123','Fabp5','Epsti1','Serpinb6b','Batf3')
FeaturePlot(myeloid_cells, features = DC3, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

```{r fig.height=x1*2, fig.width=9, echo=FALSE, warning=FALSE}
p1 <- VlnPlot(myeloid_cells, features = 'Fscn1', split.by = 'Sample' , pt.size = 0)
p2 <- VlnPlot(myeloid_cells, features = 'Ccr7', split.by = 'Sample' , pt.size = 0)
p3 <- VlnPlot(myeloid_cells, features = 'Batf3', split.by = 'Sample' , pt.size = 0)
grid.arrange(p1,p2,p3,ncol = 1)
```

### Granulocytes Markers  
```{r fig.height=x1*1, fig.width=12, echo=FALSE}
FeaturePlot(myeloid_cells, label= T, features = c('S100a8', 'S100a9','Retnlg'), pt.size = 1 , ncol = 3, order = T, reduction = 'tsne')
```

### mac1
```{r fig.height=x1*4, fig.width=12, echo=FALSE}
mac1 <- c('Cd68','Fcgr3','Fcgr1','Ccl17','C1qa','Fcrls','Cxcl16','Ccr5','Ccl12','Mafb')
FeaturePlot(myeloid_cells, features = mac1, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

```{r fig.height=x1*2, fig.width=9, echo=FALSE, warning=FALSE}
p1 <- VlnPlot(myeloid_cells, features = 'Fcgr3', split.by = 'Sample' , pt.size = 0)
p2 <- VlnPlot(myeloid_cells, features = 'Ccl17', split.by = 'Sample' , pt.size = 0)
grid.arrange(p1,p2,ncol = 1)
```


### mac2
```{r fig.height=x1*3, fig.width=12, echo=FALSE}
mac2 <- c('Gpnmb','Mfge8','Fabp5','Rilpl2','Spp1','Pdgfa','Cd63')
FeaturePlot(myeloid_cells, features = mac2, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

### mac3
```{r fig.height=x1*3, fig.width=12, echo=FALSE}
mac3 <- c('Alox15','Saa3','Prg4','Serpinb2','C4b','F5','Slpi','Icam2')
FeaturePlot(myeloid_cells, features = mac3, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

### mac4
```{r fig.height=x1*2, fig.width=12, echo=FALSE}
mac4 <- c('Chil3','Plet1','Tcf7l2','Il18')
FeaturePlot(myeloid_cells, features = mac4, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

### M2
```{r fig.height=x1*1, fig.width=12, echo=FALSE}
M2 <- c('Cd69','Mrc1','Il12a')
FeaturePlot(myeloid_cells, features = M2, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```

```{r fig.height=x1*1, fig.width=9, echo=FALSE, warning=FALSE}
p1 <- VlnPlot(myeloid_cells, features = 'Cd69', split.by = 'Sample' , pt.size = 0)
p2 <- VlnPlot(myeloid_cells, features = 'Mrc1', split.by = 'Sample' , pt.size = 0)
grid.arrange(p1,p2,ncol = 1)
```


### T cell contamination
```{r eval=FALSE, fig.height=x1*2, fig.width=12, include=FALSE}
Tcells <- c('Cd3g','Cd3d','Cd8a','Prf1')
FeaturePlot(myeloid_cells, features = Tcells, label= T,pt.size = 1.2 ,ncol = 3, order = T, reduction = 'tsne')
```



```{r fig.height=x1*2, fig.width=9, echo=FALSE, warning=FALSE}
p1 <- VlnPlot(myeloid_cells, features = 'Il2ra', split.by = 'Sample' , pt.size = 0)
p2 <- VlnPlot(myeloid_cells, features = 'Il2rb', split.by = 'Sample' , pt.size = 0)
p3 <- VlnPlot(myeloid_cells, features = 'Pdcd1', split.by = 'Sample' , pt.size = 0)
grid.arrange(p1,p2,p3,ncol = 1)
```


































<!--
################## keren's myeloid code

Clusters
---------------

```{r eval=FALSE, echo=FALSE, fig.height=5, fig.width=10}
BF.obj <- readRDS('Vitiligo.3integrgate.rds')
BF.obj$Sample <- factor(x = BF.obj$Sample, levels = c('B_before', 'B_after', 'F_before', 'F_after'))
p1 <- DimPlot(BF.obj,reduction="tsne", pt.size = 1, label = TRUE, label.size = 5) + theme(legend.position = 'none')
p2 <- DimPlot(BF.obj,reduction="tsne", group.by = 'Sample', pt.size = 1, label.size = 5)
p2+p1+plot_layout(guides = "collect")+plot_annotation(tag_levels = 'A') 
```

Barplots
---------------

```{r eval=FALSE, echo=FALSE, fig.height=4, fig.width=10}
frque <- table(Idents(BF.obj), BF.obj$Sample)
frque <- as.data.frame(frque)
frque <- frque %>% dplyr::rename(Cluster = Var1, orig.ident = Var2)
frque$orig.ident <- factor(frque$orig.ident, levels=c('B_before', 'B_after', 'F_before', 'F_after'))

frque <- ddply(frque, .(orig.ident),  transform, percentperstatus   = Freq/sum(Freq))
frque <- ddply(frque, .(orig.ident),  transform, percentperstatus   = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, percentpercluster  = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, normalizedppstatus = percentperstatus/sum(percentperstatus)*100)
frque <- ddply(frque, .(orig.ident),  transform, normalizedpcluster = percentpercluster/sum(percentpercluster))

p1 <- ggplot(frque, aes(x = Cluster, y = normalizedppstatus, fill = orig.ident)) +
 theme_minimal() +
 geom_bar(stat = "identity", width = 0.7,position="dodge") +
 ggtitle("Normalized Cluster Counts") +
 ylab("Normalized Proportions in %") +
 theme(
   axis.text.x  = element_text(size = 11, color = "black"),
   axis.text.y  = element_text(size = 11, color = "black"),
   axis.title.x = element_text(size = 13, color = "black"),
   axis.title.y = element_text(size = 13, color = "black"),
   title = element_text(size = 13),
   legend.justification = "top",
   panel.border = element_blank()) +
 geom_hline(yintercept = 25, linetype='dotted') 

p2<-ggplot(frque, aes(x= Cluster, y= Freq, fill = orig.ident)) +
 theme_minimal() +
 geom_bar(stat = "identity", width = 0.7) +
 ggtitle("Cluster Counts") + ylab("Cell counts\n") +
 theme(
   axis.text.x  = element_text(size = 11, color = "black"),
   axis.text.y  = element_text(size = 11, color = "black"),
   axis.title.x = element_text(size = 13, color = "black"),
   axis.title.y = element_text(size = 13, color = "black"),
   title = element_text(size = 13),
   legend.justification = "top",
   panel.border = element_blank())

p2+p1+plot_layout(guides = "collect")+plot_annotation(tag_levels = 'A') 
```

Markers
=====



Jak STAT 
---------------
```{r eval=FALSE, cache=T, fig.height=2*2, echo=FALSE, warning=FALSE}
p1 <- VlnPlot(BF.obj, features = 'STAT1', split.by = 'Sample', pt.size = 0)
p2 <- VlnPlot(BF.obj, features = 'STAT2', split.by = 'Sample', pt.size = 0)
p3 <- VlnPlot(BF.obj, features = 'STAT3', split.by = 'Sample', pt.size = 0)
p4 <- VlnPlot(BF.obj, features = 'STAT4', split.by = 'Sample', pt.size = 0)
p5 <- VlnPlot(BF.obj, features = 'STAT5A', split.by = 'Sample', pt.size = 0)
p6 <- VlnPlot(BF.obj, features = 'STAT6', split.by = 'Sample', pt.size = 0)
STAT_BF <- grid.arrange(p1,p2,p3,p4,p5,p6,nrow = 2,ncol = 3)
ggsave("STAT_BF.pdf",STAT_BF, width = 40, height = 22, units = "cm")
```

skin homing
---------------
```{r eval=FALSE, cache=T, fig.height=2*2, echo=FALSE}
to_skin <- c('CCR4','CCR10',"CCR2","LY6G6C","FCGR1A")
FeaturePlot(BF.obj, features = to_skin, label.size = 8, pt.size = 1 ,label=T, ncol = 2, order = T,reduction = "tsne")
```

skin homing
---------------
```{r eval=FALSE, cache=T, fig.height=2*2, echo=FALSE, warning=FALSE}
p1 <- VlnPlot(BF.obj, features = 'CCR4', split.by = 'Sample', pt.size = 0)
p2 <- VlnPlot(BF.obj, features = 'CCR10', split.by = 'Sample', pt.size = 0)
p3 <- VlnPlot(BF.obj, features = 'CCR2', split.by = 'Sample', pt.size = 0)
p4 <- VlnPlot(BF.obj, features = 'FCGR1A', split.by = 'Sample', pt.size = 0)
grid.arrange(p1,p2,p3,p4,ncol = 2)

BF_mac <- subset(BF.obj,subset = seurat_clusters %in%  c(10))
p3 <- VlnPlot(BF_mac, features = 'CCR2', split.by = 'Sample', pt.size = 0)
p4 <- VlnPlot(BF_mac, features = 'FCGR1A', split.by = 'Sample', pt.size = 0)
grid.arrange(p3,p4,ncol = 2)
```


signature
---------------
```{r eval=FALSE }
source("/Users/kerenreshef/Desktop/TAU/Madi_lab/Carmit_sc/Signature_propo/signature_utils.R")
IFNg_hallmark <- read.csv("/Users/kerenreshef/Desktop/TAU/Madi_lab/Carmit_sc/Signature_propo/signatures/Ifng hallmark sig.txt", header = TRUE)
IFNg_hallmark_sig <- IFNg_hallmark$HALLMARK_INTERFERON_GAMMA_RESPONSE %>% as.vector()
IFNg_hallmark_sig <- IFNg_hallmark_sig[-c(1)]

#vitiligo_lesons <- read.csv("/Users/kerenreshef/Desktop/TAU/Madi_lab/Carmit_sc/vitiligo_RNAseq_paper/vitiligo_patient_nonlesional_vs_disease.csv", header = TRUE)
#vitiligo_lesons_sig <- vitiligo_lesons$Gene

IFNg_hallmark_signature = make_signature(BF.obj,IFNg_hallmark_sig,idents = c('B_before', 'B_after', 'F_before', 'F_after'),is_active=FALSE, title = "signature score",format_flag = FALSE)

vitiligo_lesons_signature[3]
```


Annotation
=====

```{r eval=FALSE, fig.height=4, fig.width=7, message=FALSE, warning=FALSE,echo=FALSE}
Idents(BF.obj) <- 'seurat_clusters'
BF.obj <- RenameIdents(BF.obj,   "0" = "0_CD4 Teff",
                                 "1" = "1_CD8 Teff",
                                 "2" = "2_NK",
                                 "3" = "3_CD4 Naive", 
                                 "4" = "4_CD4 memory/Th17",
                                 "5" = "5_B cells",
                                 "6" = "6_NK/ CD8",
                                 "7" = "7_Th17/gdT",
                                 "8" = "8_B cells",
                                 "9" = "9_CD8 naive/memory",
                                "10" = "10_inflammatory monocytes"
                                                        )

p <- DimPlot(BF.obj, reduction = "tsne", label = F, label.size = 3.5)
LabelClusters(p, id = "ident",  fontface = "bold",position = "median")
#cluster 0 with few activated Tregs
```

Barplots - Annotated
---------------

```{r eval=FALSE, echo=FALSE, fig.height=5, fig.width=14}

frque <- table(Idents(BF.obj), BF.obj$Sample)
frque <- as.data.frame(frque)
frque <- frque %>% dplyr::rename(Cluster = Var1, orig.ident = Var2)
frque$orig.ident <- factor(frque$orig.ident, levels=c('B_before', 'B_after', 'F_before', 'F_after'))

frque <- ddply(frque, .(orig.ident),  transform, percentperstatus   = Freq/sum(Freq))
frque <- ddply(frque, .(orig.ident),  transform, percentperstatus   = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, percentpercluster  = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, normalizedppstatus = percentperstatus/sum(percentperstatus)*100)
frque <- ddply(frque, .(orig.ident),  transform, normalizedpcluster = percentpercluster/sum(percentpercluster))

p1 <- ggplot(frque, aes(x = Cluster, y = normalizedppstatus, fill = orig.ident)) +
 theme_minimal() +
 geom_bar(stat = "identity", width = 0.85 ,position="dodge") +
 ggtitle("Normalized Cluster Counts") +
 ylab("Normalized Proportions in %") +
 theme(
   axis.text.x  = element_text(size = 8, color = "black",angle = 30),
   axis.text.y  = element_text(size = 11, color = "black"),
   axis.title.x = element_text(size = 13, color = "black"),
   axis.title.y = element_text(size = 13, color = "black"),
   title = element_text(size = 13),
   legend.justification = "top",
   panel.border = element_blank()) +
 geom_hline(yintercept = 25, linetype='dotted') 
p1

p2<-ggplot(frque, aes(x= Cluster, y= Freq, fill = orig.ident)) +
 theme_minimal() +
 geom_bar(stat = "identity", width = 0.7) +
 ggtitle("Cluster Counts") + ylab("Cell counts\n") +
 theme(
   axis.text.x  = element_text(size = 11, color = "black",angle = 30),
   axis.text.y  = element_text(size = 11, color = "black"),
   axis.title.x = element_text(size = 13, color = "black"),
   axis.title.y = element_text(size = 13, color = "black"),
   title = element_text(size = 13),
   legend.justification = "top",
   panel.border = element_blank())
p2

p2+p1+plot_layout(guides = "collect")+plot_annotation(tag_levels = 'A') 
```

-->

