---
title: "myeloid_signatures"
author: "Michael Monsonego"
date: "2023-07-05"
output: html_document
 toc: true
editor_options: 
  chunk_output_type: console
---

=====
```{r include=FALSE}
library(Seurat)
library(tidyverse)
library(sleepwalk)
library(gridExtra)
library(plyr)
library(writexl)
library(patchwork)
library(RColorBrewer)
library(scales)
library(matlab)
library(fgsea)
library(stringr)
library(reticulate)
library(pheatmap)
library(ggpubr)
library(viridis)


  
memory.limit(10^14)
setwd("//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/3_groups")
use_python((r"(C:\Users\user\AppData\Local\Programs\Python\Python311)"), required = TRUE)
source("//asafmadilabfs/asafmadilab$/michael/Madi lab/Signature_propo/signature_utils.R")
source('D:/git_check/3-groups/sig_genes.R')
setwd("//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/3_groups")
Tcells <- readRDS("//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/3_groups/Objects/T cells/T cells_object.rds")
```


```{r}
oxphos <- c("Abcd1","Afg1l","Ak4","Atp7a","Atpsckmt","Bid","Ccnb1","Cdk1","Chchd10","Coa6","Coq7","Coq9","Cox4i2","Cox7a1","Cyc1","Cycs","Dguok","Dld","Dnajc30","Fxn","Gadd45gip1","Iscu","Msh2","mt-Atp6","mt-Atp8","mt-Co1","mt-Co2","mt-Co3","mt-Cytb","mt-Nd1","mt-Nd2","mt-Nd3","mt-Nd4","mt-Nd4l","mt-Nd5","mt-Nd6","Mtch2","Myc","Ndufa1","Ndufa10","Ndufa11","Ndufa12","Ndufa13","Ndufa2","Ndufa3","Ndufa5","Ndufa6","Ndufa7","Ndufa8","Ndufa9", "Ndufab1", "Ndufaf1", "Ndufc1", "Ndufs1", "Ndufs2","Ndufv1", "Nipsnap2", "Nupr1", "Pde12", "Pde2a", "Pink1", "Ppif", "Sdha","Sdhaf2","Shmt2","Slc25a23","Slc25a33","Stoml2","Tefm","Tmem135","Tnf","Uqcc2","Uqcc3","Uqcr10")

oxphos_sig <- make_signature(Tcells, oxphos,idents = c("D","A","B"), format_flag = TRUE)
oxphos_sig_obj <- oxphos_sig[[1]]
oxphos_sig[[3]]
ggsave("Plots/T/oxphos_sig_box.png", width = 20, height = 20, units = "cm")
oxphos_sig[[2]]
ggsave("Plots/T/oxphos_sig_tsne.png", width = 20, height = 20, units = "cm")

# violin plot per treatment per cluster
gglist <-  list()
name <- "oxphos"
for(clus in levels(oxphos_sig_obj$seurat_clusters)){
  print(clus)
  obj <- subset(oxphos_sig_obj, subset = seurat_clusters == clus)
  p <- SignatureScore(obj, 'SigUint') + ggtitle(obj@active.ident)
  gglist[[(as.numeric(clus)+1)]] <- p
}
cowplot::plot_grid(plotlist = gglist, ncol = 4, nrow = 2) + 
      ggtitle(name)
ggsave(file = "Plots/T/oxphos_sig_per_cluster_treatment.png", dpi=300, width=16, height=10)

```

```{r}
glycolysis <- c("Pfkm", 'Psmc4', 'Nup85', 'Ppha1', 'Cdk1', "Cenpa", "Gpi", "Nup155", "Gpc1", "Hk2","Aldoc","Pfkl","Nup85","Nup155", "Tpi1","Adpgk","Pfkfb1","Pfkfb4","Hk3", "Pfkfb2","Pfkfb3","Nup35","Ndc1","Gnpda2", "Aldoa","Pgm2l1","Pkm","Nup93","Pfkm","Nup54",'Nup37', 'Gpi1', 'Aaas',"Nup205",'Bpgm','Nup133',"Nup43","Nup88",'Nupl2','Nup160',"Gnpda1","Nup188","Nup107","Pom121","Gapdh","Eno1b","Eno3","Gapdhs","Pgk1","Eno1",'Nup98',"Seh1l","Nup62","Aldoa")
#M# here the results are for c("D", "A", "B") even though idents dont show B(it creates an error for some reason)
glycolysis_sig <- make_signature(Tcells, glycolysis,idents = c("D","A"), format_flag = TRUE)
glycolysis_sig_obj <- glycolysis_sig[[1]]
glycolysis_sig[[3]]
ggsave("Plots/T/glycolysis_sig_box.png", width = 20, height = 20, units = "cm")
glycolysis_sig[[2]]
ggsave("Plots/T/glycolysis_sig_tsne.png", width = 20, height = 20, units = "cm")

# violin plot per treatment per cluster
gglist <-  list()
name <- "glycolysis"
for(clus in levels(glycolysis_sig_obj$seurat_clusters)){
  print(clus)
  obj <- subset(glycolysis_sig_obj, subset = seurat_clusters == clus)
  p <- SignatureScore(obj, 'SigUint') + ggtitle(obj@active.ident)
  gglist[[(as.numeric(clus)+1)]] <- p
}
cowplot::plot_grid(plotlist = gglist, ncol = 4, nrow = 2) + 
      ggtitle(name)
ggsave(file = "Plots/T/glycolysis_sig_per_cluster_treatment.png", dpi=300, width=16, height=10)

```


```{r}
il2 <- c("Shc1","Stat5b","Lck","Stat5a","Jak3","Syk","Csnk2a1","Elk1","Grb2","Hras","Il2","Il2ra","Il2rb","Map2k1","Sos1","Csnk2a2","Fos","Jun","Mapk3","Il2rg","Mapk8","Raf1","Jak1")
il2_sig <- make_signature(Tcells, il2,idents = c("A","D"), format_flag = TRUE)
il2_sig_obj <- il2_sig[[1]]
il2_sig[[3]]
ggsave("Plots/T/il2_sig_box.png", width = 20, height = 20, units = "cm")
il2_sig[[2]]
ggsave("Plots/T/il2_sig_tsne.png", width = 20, height = 20, units = "cm")

# violin plot per treatment per cluster
gglist <-  list()
name <- "il2"
for(clus in levels(il2_sig_obj$seurat_clusters)){
  print(clus)
  obj <- subset(il2_sig_obj, subset = seurat_clusters == clus)
  p <- SignatureScore(obj, 'SigUint') + ggtitle(obj@active.ident)
  gglist[[(as.numeric(clus)+1)]] <- p
}
cowplot::plot_grid(plotlist = gglist, ncol = 4, nrow = 2) + 
      ggtitle(name)
ggsave(file = "Plots/T/il2_sig_per_cluster_treatment.png", dpi=300, width=16, height=10)



```


```{r}
il2_receptor <- c("Bad", "Bcl2", "Cbl", "Cflar", "Crkl", "E2f1", "Fas", "Fasl",	"Fos", "Grb2", "Hras", "Ikzf3", "Il2ra", "Il2rb", "Il2rg", "Irs1", "Jak1", "Jak3", "Mapk1", "Mapk3", "Myc", "Nmi", "Pik3ca", "Pik3cg", "Pik3r1", "Ptpn6", "Raf1", "Rps6kb1", "Shc1", "Socs1", "Socs3", "Sos1", "Stat5a", "Stat5b", "Syk")
il2_receptor_sig <- make_signature(Tcells, il2_receptor,idents = c("D","A","B"), format_flag = TRUE)
il2_receptor_sig_obj <- il2_receptor_sig[[1]]
il2_receptor_sig[[3]]
ggsave("Plots/T/il2_receptor_sig_box.png", width = 20, height = 20, units = "cm")
il2_receptor_sig[[2]]
ggsave("Plots/T/il2_receptor_sig_tsne.png", width = 20, height = 20, units = "cm")

# violin plot per treatment per cluster
gglist <-  list()
name <- "il2_receptor"
for(clus in levels(il2_receptor_sig_obj$seurat_clusters)){
  print(clus)
  obj <- subset(il2_receptor_sig_obj, subset = seurat_clusters == clus)
  p <- SignatureScore(obj, 'SigUint') + ggtitle(obj@active.ident)
  gglist[[(as.numeric(clus)+1)]] <- p
}
cowplot::plot_grid(plotlist = gglist, ncol = 4, nrow = 2) + 
      ggtitle(name)
ggsave(file = "Plots/T/il2_receptor_sig_per_cluster_treatment.png", dpi=300, width=16, height=10)


```


###
one object with all signatures
```{r}

CD3subset <- readRDS(file="//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/ateno+saline/Objects/T cells_object.rds")
table(CD3subset$Treatment)

signatures <- c('Tcells_Cytotoxicity', 'Tcell_chemotaxis','Tcell_Integrin_activation',
                'INTERLEUKIN_2_RECEPTOR_BINDING','Tcells_Co_Stimulatory','Tcells_Co_Inhibitory',
                'NF_KAPPAB_SIGNALING', 'Tregs_suppression')

CD3subset.sig <- CD3subset


#M# just checking how this works out: (whats 'name = ' ?, also : up -> up_sig)
check_CD3subset.sig <- CD3subset.sig
check_CD3subset.sig <- make_signature(check_CD3subset.sig, Tcells_Cytotoxicity, idents = c("A","D"), format_flag = TRUE, title = 'Tcells_Cytotoxicity')
check_CD3subset.sig_ob <- check_CD3subset.sig[[1]]
check_CD3subset.sig_ob[['Tcells_Cytotoxicity']] = (check_CD3subset.sig_ob[['Tcells_Cytotoxicity']]-min(check_CD3subset.sig_ob[['Tcells_Cytotoxicity']]))/
      (max(check_CD3subset.sig_ob[['Tcells_Cytotoxicity']])-min(check_CD3subset.sig_ob[['Tcells_Cytotoxicity']]))
#M# end of check

for (name in signatures){
    # if(name != 'Tcells_Cytotoxicity' & name != 'Tcell_chemotaxis'){next}
    print(name)
    CD3subset.sig <- make_signature(CD3subset.sig, get(name), idents = c("A","D"), format_flag = TRUE, title = name)[[1]]
    CD3subset.sig[[name]] = (CD3subset.sig[[name]]-min(CD3subset.sig[[name]]))/
      (max(CD3subset.sig[[name]])-min(CD3subset.sig[[name]])) #M# feature normaliztion (0-1)
}

saveRDS(CD3subset.sig,"//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/3_groups/Objects/T cells/CD3subset_sig.rds")

CD3subset.sig <- readRDS("//asafmadilabfs/asafmadilab$/michael/Madi lab/scRNA seq Pipeline/m/sara_teva/3_groups/Objects/T cells/CD3subset_sig.rds")



levels(CD3subset.sig$Treatment)<- c('Saline',"αPD1-Il2")
CD3subset.sig$cell.type <- paste0(CD3subset.sig@active.ident,"_", CD3subset.sig$Treatment)
levels(CD3subset.sig@active.ident) 
CD3subset.sig$cell.type <- factor(CD3subset.sig$cell.type,
                                  levels = c("0_CD8+ T cells memory differentiation_Saline",
                                             "0_CD8+ T cells memory differentiation_αPD1-Il2",
                                            "1_activated CD8+ T cells_Saline",
                                            "1_activated CD8+ T cells_αPD1-Il2",
                                            "2_effector memory-like CD8 T cells_Saline",
                                            "2_effector memory-like CD8 T cells_αPD1-Il2",
                                            "3_cytotoxic CD8+ T cells_Saline",
                                            "3_cytotoxic CD8+ T cells_αPD1-Il2",
                                            "4_naive/memory CD8+ T cells_Saline",
                                            "4_naive/memory CD8+ T cells_αPD1-Il2",
                                            "5_CD4+CD8 naive/memory_Saline",
                                            "5_CD4+CD8 naive/memory_αPD1-Il2",
                                            "6_proliferating CD8+ T cells_Saline",
                                            "6_proliferating CD8+ T cells_αPD1-Il2",
                                            "7_Tregs_Saline",
                                            "7_Tregs_αPD1-Il2"))
Idents(CD3subset.sig) <- 'cell.type' #M# what does this do?
counts <- CD3subset.sig[[signatures]]
CD3subset.sig[['sig']] <- CreateAssayObject(data = t(x = FetchData(object = CD3subset.sig, 
                                                                   vars = signatures)))
signatures1 <- gsub("_", "-", signatures)
counts <- AverageExpression(CD3subset.sig, assays = 'sig',slot = 'data', features = signatures1)[[1]]

# column annotation
annot_col = data.frame(Cluster = factor(rep(c("0_CD8+ T cells memory differentiation", 
                                              "1_activated CD8+ T cells",
                                          "2_effector memory-like CD8 T cells","3_cytotoxic CD8+ T cell",
                                          "4_naive/memory CD8+ T cells","5_CD4+CD8 naive/memory","6_proliferating CD8+ T cells",
                                          '7_Tregs'),
                                          c(2,2,2,2,2,2,2,2))),
                       Treatment = factor(rep(c("Saline","αPD1-Il2"),8)))
row.names(annot_col) <- colnames(counts) 
levels(annot_col$Treatment) = c("αPD1-Il2","Saline")

# colors
annot_colors <- c('#55a0fb','#ff8000')
annot_colors_2 <- viridis_pal(option = "D")(8) 
names(annot_colors) <- c("Saline","αPD1-Il2")
names(annot_colors_2) <- c("0_CD8+ T cells memory differentiation", 
                                              "1_activated CD8+ T cells",
                                          "2_effector memory-like CD8 T cells","3_cytotoxic CD8+ T cell",
                                          "4_naive/memory CD8+ T cells","5_CD4+CD8 naive/memory","6_proliferating CD8+ T cells",
                                          '7_Tregs')
annot_colors <- list(Treatment = annot_colors, Cluster = annot_colors_2)

# test labels
test_labels <- matrix('', 8, 16) 
test_labels <- pval_table(CD3subset.sig, signatures, test_labels) 


gaps_columns <- c(seq.int(length(levels(CD3subset.sig$Treatment)),
                  length(levels(CD3subset.sig$Treatment))*length(levels(CD3subset.sig$seurat_clusters)),
                  length(levels(CD3subset.sig$Treatment))))

# count rownames
counts <- counts %>% as.data.frame()
rownames(counts) <- c('Tcells_Cytotoxicity', 'Tcell_chemotaxis','Tcell_Integrin_activation',
                'INTERLEUKIN_2_RECEPTOR_BINDING','Tcells_Co_Stimulatory','Tcells_Co_Inhibitory',
                'NF_KAPPAB_SIGNALING', 'Tregs_suppression')
png('Plots/T/cd3_subset_sig.png',res =  300, width = 35, height = 20, units = "cm")
pheatmap(counts, scale = 'row', 
            color = colorRampPalette(rev(brewer.pal(n = 10, name = "RdBu")))(50),
            cluster_rows = F, cluster_cols = F, 
            annotation_col = annot_col,
            annotation_colors = annot_colors,
            gaps_col = gaps_columns,
            angle_col = 90,
            display_numbers = test_labels, 
            fontsize_number = 25,labels_col = rep("",16),
            border_color = "black"
            )
dev.off()

#M# 3.9 : place left : not as nice as tomers(something about the lines, i dont know why), and pval_table() doesnt work(need to dig in) 
#M# try changing order of c("Saline","αPD1-Il2") to make saline on left in plot (?)
#M#






pval_table <- function(obj, sigs, test_labels){
  test_labels <- matrix('', 8, 16) 
  for(i in seq(length(sigs))){
    print(i)
    for (clus in levels(obj$seurat_clusters)){
      print(clus)
      
      object <- subset(obj, subset = seurat_clusters == clus)
      
      # merged_treatment <- subset(object, subset = Sample == "Control")
      merged_treatment <- subset(object, subset = Treatment == "Saline")
      
      # merged_control <- subset(object, subset = Sample == "Treatment")
      merged_control <- subset(object, subset = Treatment == "\u03b1PD1-IL2")
      
      name <- sigs[i]
      αPD1-Il2
      pval <- unlist(wilcox.test(unlist(merged_control[[paste0(name)]]), 
                                 unlist(merged_treatment[[paste0(name)]]), 
                                 alternative = "two.sided"))[2]
      
      
      label <- as.character(symnum(as.numeric(pval), corr = FALSE, na = FALSE,
                                   cutpoints = c(0,0.0001, 0.001, 0.01, 0.05,1),
                                   symbols = c('****',"***", "**", "*", "")))
      
      col <- as.numeric(clus)+1
      test_labels[i,(2*col)] <- label
  }
  }
  return(test_labels)
}

```

```{r}
library(pheatmap)

# Data 
set.seed(8)
m <- matrix(rnorm(200), 10, 10)
colnames(m) <- paste("Col", 1:10)
rownames(m) <- paste("Row", 1:10)

# Heat map
pheatmap(m)








```












